[project]
name = "ee_raster_calculators"
version = "0.1.0"
authors = [{ name = "Ryan Hamilton", email = "ryan.hamilton@ec.gc.ca" }]


[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"
